name: Run Generate Posts Script
description: Run Generate Posts Script
author: Ismail BOZKURT <ismailbozkurtr@gmail.com>
inputs:
  token:
    description: Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    required: true
  deploy_url:
    required: true
runs:
  using: docker
  image: Dockerfile