# .github/actions/update_posts/action.yml
name: "Update Posts Index"
description: "Generate posts.md from content/blog/**/*.md"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run generate_posts.py
      run: |
        python .github/actions/app/generate_posts.py
      shell: bash

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update posts index"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
      shell: bash
