name: Update Posts Index

on:
  push:
    branches:
      - main

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run generate_posts.py
        run: python .github/actions/app/generate_posts.py

      - name: Commit and push changes  
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the file
          git add content/pages/posts.md

          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Update posts index"

          # Authenticated push
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
