on: push
name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # ← fixed
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script (generate_posts.py)
        run: python .github/scripts/generate_posts.py

      - name: Commit updated posts.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content/pages/posts.md
          git diff --cached --quiet || git commit -m "Update posts index"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main


      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          # TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
